db_name: "billboard.db"
table_name: "billboard"
base_url: "https://www.billboard.com/charts"
max_retries: 2

chart_names:
  - "hot-100"
  - "billboard-200"
  - "artist-100"

title_tag: "c-title a-no-trucate a-font-primary-bold-s"
artist_tag: "c-label a-no-trucate a-font-primary-s"
date_tag: "a-chart-datepicker-container"
rank_tag: "c-label a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet"
